### ISSUE TITLE
[Suggestion] Option to centralize and resize player

### ISSUE THREAD

**Issue by InitialDet** [Nectres/animos#12]
Without being in fullscreen, the player is just too small and in weird spot. It would be nice to be able to centralize it and maybe manually resize it so it can fit well in my current monitor, like making it 150% larger. 

![2022-12-07](https://user-images.githubusercontent.com/13919114/206281055-41ebd1d1-f004-478d-bfd1-83e3a27ac3b8.png)

Also a soft(?) fullscreen option would be useful, making the player fullscreen inside app only and not taking the entire monitor.

**Comment by Nectres** [comment]
Making the video player responsive to take up 60% of the screen and the rest to show episodes would be enough, right?

For the soft fullscreen, can you use the PIP option in the video player, resize it to your liking?

**Comment by InitialDet** [comment]
Taking up to 60% of the screen sounds like a good idea. I just think the most important thing is having the player centralized (if possible),

**Comment by Nectres** [comment]
This is how it is supposed to look, I have not made everything responsive so on high resolutions it deviates from this design.

![image](https://user-images.githubusercontent.com/12008678/206529794-04cb6024-44e5-42e6-97ba-ca1a02d68b0f.png)

If I were to center the player, I don't think I would be able to show the episode names beside it.

I can scale the text, headings and player and make it apt for the resolution. 

What is the resolution you are using?

**Comment by Nectres** [comment]
Huh, that's really weird. My resolution is 1920x1080 as well. 

Maybe having multiple layouts could be a thing. You can select layouts in the settings page where one of it is centred player with episodes in the bottom. I will add it to the roadmap but will probably take a while

For now, I will fix the original layout to look proper in all resolutions

**Comment by Nectres** [comment]
![image](https://user-images.githubusercontent.com/12008678/206621468-85c95f1b-55e7-4381-8acc-e26fb9aa009b.png)
Looks good?

**Comment by InitialDet** [comment]
That looks perfect, very nice.
