### ISSUE TITLE
Showing "Anime not Available" on clicking any anime

### ISSUE THREAD

**Issue by Aeropro4** [Nectres/animos#20]
Issue: As shown in the title
Image:
![image](https://user-images.githubusercontent.com/113044496/210127237-0bfc2213-2a10-4341-b8fa-d98d1b60da92.png)

**Comment by thaYt** [comment]
This is fixed but has not been released; for the download you can go to the [discord](https://discord.gg/TdfwMSXjeP).
Nectres will put out a release when he can

**Comment by Aeropro4** [comment]
> This is fixed but has not been released; for the download you can go to the [discord](https://discord.gg/TdfwMSXjeP).
> Nectres will put out a release when he can 

K thanks
