### ISSUE TITLE
I've never worked on a Svelte desktop app, suggestions from anyone on how to get started working with the source code from a Github checkout? Thank you.

### ISSUE THREAD

**Issue by BitOneZero1** [Nectres/animos#25]
I'm on Ubuntu 22.04 x64 development system using Visual Studio Code.

Can someone please give some basics on what to run, npm install, etc? To build a edit/run development environment?

Thank you.

**Comment by thaYt** [comment]
hey, usually cloning and running `npm run build` then `npm run dev` works to fully set everything up.
